### ISSUE TITLE
Peer-to-Peer Code review

### ISSUE THREAD

**Issue by Jaymelfah** [svitalis123/leaderboard#4]
#### We noticed some few things you can incorporate into your project to improve user experience:
- You might consider making your page more responsive on mobile devices
- You can also add some padding to the score items to improve the UI.
- There is also a typo in your Readme on 'Scores'. You probably will want to correct that.
- You might also want to remove the Acknowledgement section from the Readme altogether if there is no one you want to acknowledge.

**Comment by svitalis123** [comment]
Hello Jay thank you for the suggestions done :heavy_check_mark:
